import {
  PayCircleOutlined,
  ShoppingCartOutlined,
  MessageOutlined,
  TeamOutlined,
  UserOutlined,
  DashboardOutlined,
  ApiOutlined,
  CameraOutlined,
  EditOutlined,
  CodeOutlined,
  LineOutlined,
  BarChartOutlined,
  AreaChartOutlined,
  ProfileOutlined,
  FormOutlined,
  UnorderedListOutlined,
  PicRightOutlined,
  TagsOutlined,
  DeleteOutlined,
  StopTwoTone,
  DeleteFilled,
  UploadOutlined,
  FileProtectOutlined,
  BookOutlined,
} from '@ant-design/icons'

export default {
  'pay-circle-o': <PayCircleOutlined />,
  'shopping-cart': <ShoppingCartOutlined />,
  'camera-o': <CameraOutlined />,
  'line-chart': <LineOutlined />,
  'code-o': <CodeOutlined />,
  'area-chart': <AreaChartOutlined />,
  'bar-chart': <BarChartOutlined />,
  'posts': <ProfileOutlined />,
  message: <MessageOutlined />,
  team: <TeamOutlined />,
  dashboard: <DashboardOutlined />,
  user: <UserOutlined />,
  api: <ApiOutlined />,
  edit: <EditOutlined />,
  create: <FormOutlined />,
  list: <UnorderedListOutlined />,
  category: <PicRightOutlined />,
  tag: <TagsOutlined />,
  trash: <DeleteFilled style={{color:'red'}}/>,
  'trash-outline' : <DeleteOutlined  style={{color:'red'}}/>,
  upload: <UploadOutlined />,
  stop: <StopTwoTone />,
  term: <FileProtectOutlined />,
  vouchers: <BookOutlined />,
}